{"name": "test_empty_notes_list", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'No notes found' in 'Welcome to Takenote!\\nNote options\\nNotes'\n +  where 'Welcome to Takenote!\\nNote options\\nNotes' = get_notes()\n +    where get_notes = <pages.notes_page.NotesPage object at 0x000001C2972E2D70>.get_notes", "trace": "notes_page = <pages.notes_page.NotesPage object at 0x000001C2972E2D70>\n\n    def test_empty_notes_list(notes_page):\n        notes_page.navigate(\"https://takenote.dev/app\")\n>       assert \"No notes found\" in notes_page.get_notes()\nE       AssertionError: assert 'No notes found' in 'Welcome to Takenote!\\nNote options\\nNotes'\nE        +  where 'Welcome to Takenote!\\nNote options\\nNotes' = get_notes()\nE        +    where get_notes = <pages.notes_page.NotesPage object at 0x000001C2972E2D70>.get_notes\n\ntests\\test_notes.py:33: AssertionError"}, "attachments": [{"name": "screenshot", "source": "7b692ede-4727-4b28-b19d-d49bc86bb07d-attachment.png", "type": "image/png"}], "start": 1741166456012, "stop": 1741166457572, "uuid": "c42987d6-531c-4cd5-8ca3-1d4dab5ca3c5", "historyId": "043d8b6728704d089f78219773fc68de", "testCaseId": "043d8b6728704d089f78219773fc68de", "fullName": "tests.test_notes#test_empty_notes_list", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_notes"}, {"name": "host", "value": "DESKTOP-GIDTMH7"}, {"name": "thread", "value": "10884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_notes"}]}